[project]
name = "blender-mit-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "anthropic>=0.75.0",
    "bpy>=5.0.0",
    "mathutils>=3.3.0",
    "mcp>=1.22.0",
    "python-dotenv>=1.2.1",
]
